# Generated by Django 4.2 on 2023-07-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organización'),
        ),
    ]
