# Generated by Django 4.2 on 2023-07-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_historicaluser_organization_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='organization',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Organización'),
        ),
    ]
