# Generated by Django 4.2 on 2023-04-24 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neutral', models.DecimalField(decimal_places=2, max_digits=5)),
                ('disgust', models.DecimalField(decimal_places=2, max_digits=5)),
                ('surprise', models.DecimalField(decimal_places=2, max_digits=5)),
                ('angry', models.DecimalField(decimal_places=2, max_digits=5)),
                ('happy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('registred', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
