# Generated by Django 4.2 on 2023-04-27 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emotion_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emotions',
            options={'verbose_name': 'Deteccion', 'verbose_name_plural': 'Detecciones'},
        ),
        migrations.AlterField(
            model_name='emotions',
            name='angry',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Enojo'),
        ),
        migrations.AlterField(
            model_name='emotions',
            name='disgust',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Disgusto'),
        ),
        migrations.AlterField(
            model_name='emotions',
            name='happy',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Felicidad'),
        ),
        migrations.AlterField(
            model_name='emotions',
            name='neutral',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Neutral'),
        ),
        migrations.AlterField(
            model_name='emotions',
            name='registred',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='emotions',
            name='surprise',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Sorpresa'),
        ),
        migrations.CreateModel(
            name='HistoricalEmotions',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('neutral', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Neutral')),
                ('disgust', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Disgusto')),
                ('surprise', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Sorpresa')),
                ('angry', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Enojo')),
                ('happy', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Felicidad')),
                ('registred', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de registro')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Deteccion',
                'verbose_name_plural': 'historical Detecciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
